const BAD_REQUEST = 400;
const NOT_AUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const DEFAULT_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  NOT_AUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT_ERROR,
  DEFAULT_ERROR,
};
